### ISSUE TITLE
Failed to Import Widget Error

### ISSUE THREAD

**Issue by rfitkin90** [WesBosch/ReBuff#1]
Hi, thanks for taking over development on this plugin.

I'm getting a "Failed to Import Widget" error when I try to import any XIVAuras string.

Also, the widgets I used in XIVAuras were customized by me and I never exported them to a string. Since it's not possible to open XIVAuras anymore to export them, will there be any way to get old XIVAura widgets from the XIVAuras.json file and convert them over to ReBuff?

Edit: I'm trying to redo my auras from scratch incase it's not possible to recover my old ones and I'm not finding an option to desaturate icons. Would it be possible to add this?

**Comment by Cellane** [comment]
@rfitkin90 I had luck converting my XIVAuras configuration into ReBuff by doing the following:

1. Go to `%AppData%\XIVLauncher\pluginConfigs`
2. Duplicate the `XIVAuras` folder, name the copy `ReBuff`
3. Enter the `ReBuff` folder, rename `XIVAuras.json` to `ReBuff.json`
4. Search and replace the following:
    - `XIVAuras.Config` -> `ReBuff.Config`
    - `0.2.5.0` -> `0.3.0.1`
    - `AuraList` -> `WidgetList`
    - `Auras` -> `Widgets`
    - `Aura` -> `Widget`

(It’s possible that the replacements 3️⃣ and 4️⃣ could be omitted as the step 5️⃣ basically does the same, but I haven’t tried it…)

@WesBosch If confirmed working, it might be worth adding this into the `README`. Let me know if you want me to open a pull request.

**Comment by WesBosch** [comment]
Old auras might not be fully compatible with the new data structure since a lot of stuff involving "auras" were renamed, I also changed some things around to make Bars work and tried to maintain compatibility with existing presets but I haven't fully tested that. You can still use the XIVAuras release from Tischel https://github.com/Tischel/XIVAuras if you still need the old ones and can't recreate them or get them working with the workaround Cellane posted. 

Desaturating icons is something I didn't notice I broke, I'll be looking into it shortly. Thanks for the report

**Comment by WesBosch** [comment]
Alright, a quick and dirty update was just pushed to put the desaturate icon toggle back, sorry about that!  If the above workaround is confirmed to work and nothing else has gone missing, I'll add that to the readme for any future users.

Please let me know if there are any old features that might be missing, my workflow is hectic and this is mostly just a hobby for myself so some things might have gotten lost in translation. 🙏

**Comment by rfitkin90** [comment]
@Cellane Yes, that worked! Thank you!

The only change I had to make was changing step 1 from "`XIVAuras.Config` -> `ReBuff.Config`" to "`XIVAuras` -> `ReBuff`", since there were some instances of "XIVAura" not ending in ".config" that got left behind.

@WesBosch And thank you for fixing the icon desaturation. I'm yet to find any other missing features but I'll certainly let you know if I do.

**Comment by WesBosch** [comment]
I'm glad to hear the workaround works!

I'll look into reinstating a bit of code from the old xivauras specifically to allow importing old-format Auras. I had been trying to distance this plugin from "auras" since the name itself was leading to a lot of confusion in regards to potential first-party support, but I can probably get away with some behind the scenes instances. 

Thanks again for bringing this up, I didn't use any presets that weren't my own so it never came up in my testing.

**Comment by LukeDowell** [comment]
@Cellane I can confirm your workflow is successful with the latest version of ReBuff. I have non-trivial auras for almost every job and they were imported successfully into ReBuff. 

I imagine Dalamud restricts the ability to modify files outside of the plugin-specific folders, but having some kind of auto-import would be nice and smooth adoption. I'll tinker with it later today and see if it's possible!

**Comment by ransley1** [comment]
I'm having issues following the above steps to import widgets. The Rebuff.json file keeps reverting back to normal, even after setting as read only. Something will rename the file that I modified into Rebuff.json.bak and replace the original file completely. As an aside, any widgets that I create in-game will disappear when I log back into the game. I can create a separate issue for that if necessary.

**Comment by WesBosch** [comment]
Both of those seem related, and my guess would be file permissions errors. Unfortunately that's outside my wheel of experience so I'm not sure what the solution would be. Have you been running ffxiv or xllauncher as admin? If so, you really should not be.

**Comment by Cellane** [comment]
@ransley1 Sorry if it’s obvious, but just to double-check, you’re altering the config file while the game is turned off, right?

**Comment by tjabba** [comment]
Tried the steps to get the old XA into rebuff, but didnt work :( Anyone knows where to find widgets for ReBuff?

**Comment by tjabba** [comment]
> I'm having issues following the above steps to import widgets. The Rebuff.json file keeps reverting back to normal, even after setting as read only. Something will rename the file that I modified into Rebuff.json.bak and replace the original file completely. As an aside, any widgets that I create in-game will disappear when I log back into the game. I can create a separate issue for that if necessary.

I have the exact same issue

**Comment by ransley1** [comment]
To update: I'm not sure what happened, but I'll try to explain what fixed my issue. All of my 'widgets' are now working.

1. Followed the steps from @Cellane above.
2. Made the file ReBuff.Config read only.
3. Played the game for the night.
4. Decided to test further and disabled read only. (Probably irrelevant, but including for consistency.)
5. Deleted the ReBuff folder from `%AppData%\XIVLauncher\pluginConfigs`.
6. Followed the exact steps that @Cellane provided [here](https://github.com/WesBosch/ReBuff/issues/1#issuecomment-1563788692).
7. Loaded the game up the next day, PC was not restarted.
8. Widgets working.

I have no idea, but it works. It's entirely possible that there's a user error or Dalamud decided to allow the mod to function. ACT was running the background while I was originally making the changes (but was closed when I made the most recent changes), so there's a possibility that ACT was somehow interfering as that is run as administrator. XIVLauncher is not run as administrator.

**Comment by rfitkin90** [comment]
I ran into the same issues others are having when following Cellane's exact steps. I assumed it was because replacing the `XIVAuras.config`s instead of the `XIVAuras`s left some instances of `XIVWidgets` in the json which didn't look right to me. And the plugin couldn't read the json so it just made a new one from scratch and backed up your one.

**Comment by WesBosch** [comment]
Hey everyone, I've been looking into different ways to resolve this issue and I think the most effective method would be to rebase the project and return a lot of the aura references internally. In my testing, this allows importing previously existing Auras (Tested with VondUI import strings) and in my case it reset my configs to what I was using before making ReBuff. I do not have an old XIVAuras installation to test, but I would like to hear feedback on how the new release interacts with existing configs.

Since this update changes the internal name, you may need to remove the old release, restart the game, then install the new release. I didn't expect anyone to actually use this project yet, so I did not anticipate the issues that changing the internal names would cause. I hope that this update resolves that issue, or at least makes it easier to resolve.

As a result of this change new configs for ReBuff, such as those made with the instructions in this thread, will probably not be compatible and any new widgets will likely need to be remade. Sorry for the inconvenience. 

_____________________________________________________________________________________________________________________________________

This is primarily a personal project, I know very little about how much of this code works and coding in general, so I personally won't be able to provide much support on my own. If you're looking for a simple replacement to XIVAuras, then https://github.com/Tischel/XIVAuras is the officially supported legacy release. Thank you for understanding.

**Comment by MadMadaMim** [comment]
I was able to switch over all my auras using Cellane's instructions, everything is working fine. I hope you keep this version going.
