### ISSUE TITLE
No longer being serviced

### ISSUE THREAD

**Issue by MadMadaMim** [WesBosch/ReBuff#3]
I'm getting a message saying this plugin is no longer being serviced by its source repo. this is such a great plugin, I would hate to see it disappear. Is there another repo for this?

**Comment by WesBosch** [comment]
Delete the one you have, restart the game, then reinstall. I did some major changes while trying to resolve a bug with importing existing Xivauras presets so the plugin's internal name changed. This makes the game think it's gone but it can still be installed from the same repo after following the steps above.

Due to this change, existing Rebuff configs may be lost. If you have an existing Xivauras config, it should use that now (I hope) and it will be compatible with existing XIVAura import strings (Tested and confirmed working with VondUI strings) 

Sorry for the inconvenience!

**Comment by MadMadaMim** [comment]
Not having this plugin would be the inconvenience, YOU ARE AMAZING ♥
