### ISSUE TITLE
Display order with several overlaying icons and status trigger for dragon sight

### ISSUE THREAD

**Issue by baelrayneVessdren** [WesBosch/ReBuff#5]
Hi WesBosch.

Encountered some strange behavior while configuring RB for my DRG:

Display order with several overlaying icons, with different triggers:
Since WeakAuras I build groups and have several triggers for different states of a buff. I had some issues with DRG's Lance Charge.
1st trigger in the group: 

- lanceCharge_rdy with glowing border
- Trigger: Cooldown with "Action: Usable" and Status with "Status not Active"
- Some Visibility like "out of Combat" and Job to show for

So far so good. Works as intended

2nd and 3rd trigger in the group:

- lanceCharge_Buff (running) and lanceCharge_CD without glowing border
- Trigger: Status with "Status Active" / "Status not Active" and for the CD one with Cooldown <60 sec
- same Visibility as for the 1st trigger

**_Now:_** The glowing border around the 1st trigger vanishes and only appears for half a second after triggering the buff. **BUT** once I change the order of the trigger within the group, putting trigger 1 on position 2, it works again, but only for the border. The cooldown trigger is broken after I change the order. Had to remove the triggers and group and build them from scratch again. 

+++++++++++++

My second problem is with Dragon Sight and maybe there is some correlation here. 

Same procedure. Creating a group and trying to create 3 trigger. Rdy, Buff (running) and CD.

Creating Rdy works fine for the cooldown trigger (Screenshot).
![image](https://github.com/WesBosch/ReBuff/assets/131447339/fc8121db-8e1b-4d95-82f6-791cee92d05d)

Once I try to add the Status trigger it does not recognize the spell.

Tried to create the buff (running) trigger again with Status and same issue. 

Deleted the group, the trigger, etc. but to no effect. For some reason Dragon Sight seems only be usable with a  Cooldown trigger.

Maybe you have a suggestion regarding the behavior or a solution.

Thanks alot and br

**Comment by WesBosch** [comment]
I don't play DRG, but I believe Dragon Sight only has cooldown data since the buff it gets has a seperate name. If you're trying to track the buff from dragon sight, You'll probably want to track the buff for Right Eye on self and adjust some variables accordingly.

From the description of your issue, it sounds like the trigger data is conflicting in some way. You might try adjusting the IF/AND/OR states, or simply make a second icon above the first with the second trigger. Unfortunately complex trigger logic is messy and the game itself doesn't always provide the trigger data as expected (more common on caster classes I've noticed) I've been trying to come up with solutions myself for classes like AST but I haven't found anything that quite works. (This issue with complex logic was also present in the original XIVAuras as well)

**Comment by baelrayneVessdren** [comment]
You sir are absolutely right ...... The buff does have another name. Right Eye for you and left eye for the grateful recipient .... Sorry to even bother you with that :)

Regarding the other issue, I will keep an **Eye** on that. If it happens again I will try and provide screenshots. Maybe that way you can figure it out. 

Thanks for the help and fast reply.

**Comment by WesBosch** [comment]
Of course! I hope the rest works itself out, it sounds like a game-logic issue more than anything (I had similar problems trying to do the same for AST's card buffs) my solution was to split the triggers across more elements so they weren't as complex.

I'll mark this as closed for now, but do let me know if there are any more wierd issues! I'll probably be putting out a new update later this month with some job gauge stuff so that should give us more trigger options to work with for job buffs and stuff 🤞
