### ISSUE TITLE
Unknown Repository

### ISSUE THREAD

**Issue by TheMetabee** [WesBosch/ReBuff#6]
Firstly, thanks for making an update to this plugin. I'm trying to use it but I'm getting the Unknown Repository error in the plugins. Do you happen to know why? I'm using this as your link:

https://raw.githubusercontent.com/WesBosch/ReBuff/main/repo.json

Picture of error:
https://i.imgur.com/xltCt5c.png

**Comment by WesBosch** [comment]
restart the game after changing the repo, then reinstall the plugin

**Comment by TheMetabee** [comment]
I ended up installing the dll directly, but when you say "reinstall the plugin" what does that entail other than relinking the repo json?

**Comment by WesBosch** [comment]
Be sure you've switched the repo link in your dalamud settings to use rebuff's instead of xivauras, restart the game, then if you already have xivauras installed, uninstall it before installing ReBuff. 

You can't have both at the same time since they use the same internal name. ReBuff should pick up your existing xivauras's config file automatically.

**Comment by TheMetabee** [comment]
Thanks. You can consider this resolved.
